### ISSUE TITLE
Carousel eruit

### ISSUE THREAD

**Issue by LianeWilke** [openstate/openstate-site#11]
voorlopig mag in de plaats van de carousel de kernboodschap (zie issue #9 ) komen. 
Ik zou daaronder het liefst ruimte houden voor 4 foto's: cultuur, onderwijs, zorg en transparantie (zie issue #8 )

**Comment by dsbaars** [comment]
Leesvoer over sliders/carousels: http://www.hellopixels.nl/een-slider-op-je-homepage-is-slecht-voor-je-conversie/

**Comment by ajslaghu** [comment]
in huidige staging geimplementeerd
