### ISSUE TITLE
Responsive

### ISSUE THREAD

**Issue by LianeWilke** [openstate/openstate-site#13]
website responsive maken

**Comment by bennokr** [comment]
In framework (s7 of zo) oa:
- hamburgermenu met alleen hoofd items
- homepage thema knoppen met foto's of icoontjes (zie nu.nl)

https://github.com/reduxframework/redux-framework

**Comment by siccovansas** [comment]
Added in the new Sage-based OSF theme: https://github.com/openstate/open-state-theme
