### ISSUE TITLE
Fix logo image link

### ISSUE THREAD

**Issue by siccovansas** [openstate/openstate-site#15]
Het logo linksboven is nu geen link naar de homepage. In plaats daarvan zit er de transparante tekst, 'Open State Foundation', onder (die je ziet als je alles op de pagina selecteert). Deze tekst fungeert sneaky als link ;). De tekst/link area overlapt echter niet met het logo waardoor je met je cursor over het plaatje kan hooveren en dan soms wel en soms niet op de link kan klikken.

Kan de tekstlink dus verwijderd worden en het logo veranderd worden in een link?

![screenshot from 2015-06-08 16 23 35](https://cloud.githubusercontent.com/assets/696839/8037021/c1ae5d10-0dfb-11e5-84ff-d46c97a68abb.png)

**Comment by bennokr** [comment]
Yes! Fixed by 671914040b7f3beec5c61cb09ee9f8f386a53e49

Het menu overlapte ook het logo, die zitten nu naast elkaar. Deze fix was ook (ivm css) nodig voor de grote navigatie die er aan zit te komen (#19) en kernboodschap (#9)
