### ISSUE TITLE
Navigatie & subnavigatie aanpassen

### ISSUE THREAD

**Issue by LianeWilke** [openstate/openstate-site#19]
![screen shot 2015-06-18 at 16 57 56](https://cloud.githubusercontent.com/assets/12659541/8234331/83a005e0-15db-11e5-8fd3-89e45fe88f96.png)

Deze 'subnavigatie' is (straks) niet meer nodig

**Comment by bennokr** [comment]
Zoiets:

![screen shot 2015-07-30 at 14 39 32](https://cloud.githubusercontent.com/assets/994319/8983236/e46de956-36c8-11e5-8d60-e37bf5219d8e.png)

**Comment by bennokr** [comment]
Met submenu rechts (technisch klaar, vormgeving niet):

![screen shot 2015-07-30 at 17 15 09](https://cloud.githubusercontent.com/assets/994319/8986891/99c799b8-36de-11e5-9f48-545d6937b7fb.png)
