### ISSUE TITLE
Agenda

### ISSUE THREAD

**Issue by LianeWilke** [openstate/openstate-site#20]
Een agenda mogelijkheid toevoegen op de website

**Comment by ajslaghu** [comment]
die is er al, maar wat wil je er mee? in het verleden niet gebruikt

**Comment by LianeWilke** [comment]
ik denk ook eigenlijk dat we dat niet meer nodig hebben, want wordt rommelig op de homepage vrees ik en zoveel "externe" activiteiten hebben we nu ook eigenlijk niet.
