### ISSUE TITLE
Apps4Europe onder community - mag die er uit?

### ISSUE THREAD

**Issue by LianeWilke** [openstate/openstate-site#26]

**Comment by LianeWilke** [comment]
Hoe relevant is dat nog?

**Comment by ajslaghu** [comment]
niet

Lex Slaghuis
GSM: 06 24687129 | lex@wikiwise.nlmailto:lex@wikiwise.nl | www.wikiwise.nlhttp://www.wikiwise.nl/ | Tel: 020 7163963

---

Van: LianeWilke notifications@github.com
Verzonden: maandag 3 augustus 2015 16:28
Aan: openstate/openstate-site
Onderwerp: Re: [openstate-site] Apps4Europe onder community - mag die er uit? (#26)

Hoe relevant is dat nog?

##

**Comment by LianeWilke** [comment]
Heb het eruit gehaald
