### ISSUE TITLE
'Meer artikelen' werkt niet goed.

### ISSUE THREAD

**Issue by tomkunzler** [openstate/openstate-site#43]
als ik op de OpenState.eu frontpage op 'alle artikelen' klik, krijg ik een overzicht met niet alleen nieuws, maar ook tools en 'over' pagina's. Dat lijkt me niet de bedoeling.

De button 'alle artikelen' linkt naar een zoekpagina: http://www.openstate.eu/nl/search/+/

Terwijl hij denk ik moet linken naar: http://www.openstate.eu/nl/search/+/page/2/

Hij zou misschien beter kunnen linken naar http://www.openstate.eu/nl/category/news/, maar dan moet er misschien een menu-item 'Zoek' bijkomen. Bovenin naast 'Contact'?

**Comment by siccovansas** [comment]
Issue ported to https://github.com/openstate/open-state-theme/issues/2
