### ISSUE TITLE
Featured images

### ISSUE THREAD

**Issue by LianeWilke** [openstate/openstate-site#5]
Featured images weer toevoegen aan blog/nieuwsberichten. 
Voorlopig uittesten in testomgeving bij de laatste 4 berichten.

Liane selecteert foto's. Samen hebben over afmetingen?

**Comment by bennokr** [comment]
De Featured Images in de nieuws-feed waren origineel **rond**. Willen we dat behouden?
Ik heb de uitlijning verbeterd, waardoor er geen problemen meer zijn met de lengte van de titels.
Er kan natuurlijk nog een en ander veranderd worden aan de witruimte, die is nu iets nauwer dan voorheen.

![screen shot 2015-06-04 at 16 54 47](https://cloud.githubusercontent.com/assets/994319/7987123/c0bf8406-0adb-11e5-93a6-813b858d3c34.png)

**Comment by LianeWilke** [comment]
ik vind het mooi, maar op deze manier ziet het er heel groot uit..?

**Comment by bennokr** [comment]
Zo is 'ie wat kleiner:

![screen shot 2015-06-12 at 12 36 45](https://cloud.githubusercontent.com/assets/994319/8128481/c44c8810-10ff-11e5-925f-f9b9dff33e0c.png)

**Comment by LianeWilke** [comment]
Beter inderdaad!

**Comment by bennokr** [comment]
Met de tekst uitgelijnd zoals het originele ontwerp is het nu gebalanceerd:

![screen shot 2015-07-30 at 10 44 18](https://cloud.githubusercontent.com/assets/994319/8979159/0c1c96e4-36a8-11e5-87d4-d264e27f5e1a.png)
