### ISSUE TITLE
Mailchimp-plug in toevoegen 

### ISSUE THREAD

**Issue by LianeWilke** [openstate/openstate-site#6]
Tekst: Join our mailing list / Blijf op de hoogte

**Comment by bennokr** [comment]
Ik kwam een oude versie van de stijl voor de mailinglist tegen in de code!
In 4fe26e9c5b1c8712dab164df4982d172eceabc58 heb ik gereconstrueerd hoe ik denk dat het er uit heeft gezien:

![screen shot 2015-06-04 at 16 58 42](https://cloud.githubusercontent.com/assets/994319/7986995/28b78870-0adb-11e5-8d13-4f1470e10ce2.png)

Zoiets?

**Comment by LianeWilke** [comment]
I like it!
