### ISSUE TITLE
Toevoegen ruimte voor "kernboodschap" Open State

### ISSUE THREAD

**Issue by LianeWilke** [openstate/openstate-site#9]
Zie voorbeeld op Open Cultuur Data.nl 

Zin: Open State Foundation bevordert digitale transparantie door het ontsluiten van open data en door de ontwikkeling van innovatieve en creatieve toepassingen te stimuleren.

![screen shot 2015-05-29 at 15 40 28](https://cloud.githubusercontent.com/assets/12659541/7883736/10a472be-0619-11e5-86a5-5e622e2276a9.png)

**Comment by bennokr** [comment]
Grote grijze cursieve tekst op lichtblauwe achtergrond:

![screen shot 2015-07-30 at 10 46 43](https://cloud.githubusercontent.com/assets/994319/8979347/51e4f5d0-36a9-11e5-9a50-c19a67f3f0b2.png)
